# Change these first
# https://CityScope.github.io/CS_CityIO_uptime
owner: CityScope # Your GitHub username
repo: CS_CityIO_uptime # Your GitHub repository name

env:
  NOTIFICATION_SLACK = true
  NOTIFICATION_SLACK_WEBHOOK = true

# Add your sites here
sites:
  - name: CityIO
    url: https://cityio.media.mit.edu/
    assignees:
      - yasushisakai
  - name: CityScope
    url: https://cityscope.media.mit.edu/
    assignees:
      - RELNO
  - name: CityScope Editor
    url: https://cityscope.media.mit.edu/CS_cityscopeJS/?editor
  - name: CorkTown
    url: https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=corktown

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /CS_CityIO_uptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CityIO Uptime
  introTitle: "**CityIO** uses uptime, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
